### ISSUE TITLE
Erase eeprom upon flashing firmware not from menu

### ISSUE THREAD

**Issue by adeebshihadeh** [Printrbot/FirmwareUpdatr#6]
this is useful if one is using their own hex and version of Marlin or whatever firmware. My printrboard won't connect to any hosts due to invalid eeprom because it still has the custom gcode from the printrbot fork of marlin in its eeprom.

**Comment by PxT** [comment]
I'm not sure how the EEPROM settings could prevent you from connecting to a host, all it stores is things like steps per mm and acceleration speeds.  However we could send "M502" during drag-and-drop installs, that would reset any settings in EEPROM to the factory defaults.  I will add it in the next update.

**Comment by adeebshihadeh** [comment]
I don't know how either. I just read it somewhere that it is a possibility. (I am clearly not an expert on microcontrollers.) But I finally got stock marlin running on it. I suspect it had something to do with the buggy nature of the Development branch. When I switched to the Release branch, it worked fine.
